/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.imdea.vcd;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MessageSet extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6513307926713245747L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MessageSet\",\"namespace\":\"org.imdea.vcd\",\"fields\":[{\"name\":\"messages\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Message\",\"fields\":[{\"name\":\"hash\",\"type\":\"bytes\"},{\"name\":\"data\",\"type\":\"bytes\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MessageSet> ENCODER =
      new BinaryMessageEncoder<MessageSet>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MessageSet> DECODER =
      new BinaryMessageDecoder<MessageSet>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<MessageSet> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<MessageSet> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MessageSet>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this MessageSet to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a MessageSet from a ByteBuffer. */
  public static MessageSet fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<org.imdea.vcd.Message> messages;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MessageSet() {}

  /**
   * All-args constructor.
   * @param messages The new value for messages
   */
  public MessageSet(java.util.List<org.imdea.vcd.Message> messages) {
    this.messages = messages;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return messages;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: messages = (java.util.List<org.imdea.vcd.Message>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'messages' field.
   * @return The value of the 'messages' field.
   */
  public java.util.List<org.imdea.vcd.Message> getMessages() {
    return messages;
  }

  /**
   * Sets the value of the 'messages' field.
   * @param value the value to set.
   */
  public void setMessages(java.util.List<org.imdea.vcd.Message> value) {
    this.messages = value;
  }

  /**
   * Creates a new MessageSet RecordBuilder.
   * @return A new MessageSet RecordBuilder
   */
  public static org.imdea.vcd.MessageSet.Builder newBuilder() {
    return new org.imdea.vcd.MessageSet.Builder();
  }

  /**
   * Creates a new MessageSet RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MessageSet RecordBuilder
   */
  public static org.imdea.vcd.MessageSet.Builder newBuilder(org.imdea.vcd.MessageSet.Builder other) {
    return new org.imdea.vcd.MessageSet.Builder(other);
  }

  /**
   * Creates a new MessageSet RecordBuilder by copying an existing MessageSet instance.
   * @param other The existing instance to copy.
   * @return A new MessageSet RecordBuilder
   */
  public static org.imdea.vcd.MessageSet.Builder newBuilder(org.imdea.vcd.MessageSet other) {
    return new org.imdea.vcd.MessageSet.Builder(other);
  }

  /**
   * RecordBuilder for MessageSet instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MessageSet>
    implements org.apache.avro.data.RecordBuilder<MessageSet> {

    private java.util.List<org.imdea.vcd.Message> messages;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.imdea.vcd.MessageSet.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.messages)) {
        this.messages = data().deepCopy(fields()[0].schema(), other.messages);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MessageSet instance
     * @param other The existing instance to copy.
     */
    private Builder(org.imdea.vcd.MessageSet other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.messages)) {
        this.messages = data().deepCopy(fields()[0].schema(), other.messages);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'messages' field.
      * @return The value.
      */
    public java.util.List<org.imdea.vcd.Message> getMessages() {
      return messages;
    }

    /**
      * Sets the value of the 'messages' field.
      * @param value The value of 'messages'.
      * @return This builder.
      */
    public org.imdea.vcd.MessageSet.Builder setMessages(java.util.List<org.imdea.vcd.Message> value) {
      validate(fields()[0], value);
      this.messages = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'messages' field has been set.
      * @return True if the 'messages' field has been set, false otherwise.
      */
    public boolean hasMessages() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'messages' field.
      * @return This builder.
      */
    public org.imdea.vcd.MessageSet.Builder clearMessages() {
      messages = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MessageSet build() {
      try {
        MessageSet record = new MessageSet();
        record.messages = fieldSetFlags()[0] ? this.messages : (java.util.List<org.imdea.vcd.Message>) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MessageSet>
    WRITER$ = (org.apache.avro.io.DatumWriter<MessageSet>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MessageSet>
    READER$ = (org.apache.avro.io.DatumReader<MessageSet>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
