/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.imdea.vcd.datum;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Status {
  WRITTEN, COMMITTED, DELIVERED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Status\",\"namespace\":\"org.imdea.vcd.datum\",\"symbols\":[\"WRITTEN\",\"COMMITTED\",\"DELIVERED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
